### ISSUE TITLE
Support Shift + up/down in table-output-component

### ISSUE THREAD

**Issue by hriday-panchasara** [eclipse-cdt-cloud/theia-trace-extension#854] opened 2022-10-13 20:26 UTC
With the upgrade of AgGrid in https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/813 looks like the user is not able to select multiple rows through Shift + up/down

**Comment by hoangphamEclipse** [comment] 2022-11-16 16:17
Hello Hriday, I tested this out and looks like the user needs to focus a cell (so that it has the blue border) before Shifting up/down. If I focus on a cell, it works fine. Can you double check this?

**Comment by hoangphamEclipse** [comment] 2022-11-28 20:00
Closing this issue since confirmed that this is not a bug.

**Closed by hoangphamEclipse** 2022-11-28 20:00 UTC
Labels: bug, help wanted, Theia UI
