### ISSUE TITLE
XY Chart: Missing y-axis

### ISSUE THREAD

**Issue by ebugden** [eclipse-cdt-cloud/theia-trace-extension#628] opened 2022-01-20 15:05 UTC
Sometimes when a checkbox is selected, the chart will show a straight horizontal line down the middle of the chart and no y-axis.
* This seems to happen often with the Disk IO view (see screenshot below)
* Does this happen when the chart tries to plot an empty data set?

![image](https://user-images.githubusercontent.com/28311615/150363658-c1ce8377-3fe6-4352-bfcf-4443e249e982.png)

**Comment by bhufmann** [comment] 2023-02-27 15:20
I can't reproduce it. There were multiple improvements made to handle empty data and provide feedback to user if it's empty. I'm closing this one. Feel free to reopen if it is sill valid.

**Closed by bhufmann** 2023-02-27 15:20 UTC
Labels: bug

**Comment by ebugden** [comment] 2023-02-27 17:08
Just checked now and was also not able to reproduce. I think you're right that this was resolved in the meantime. I think the flat line was related to unhandled failed or empty analysis results and may have been solved by PRs #621 #627 

Thanks for the cleanup :pray:
